### ISSUE TITLE
Add common linter check to ensure that all operator/managers defined the resource request

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/api#172]
## What

Verify that all the operators' Deployment has resource requests set on every container. In cases where no resource requests have been supplied for CPU and memory the verification should fail, e.g;

```yml
  ...
  # TODO(user): Configure the resources accordingly based on the project requirements.
  # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    ... 
```

## Why

Kubernetes resource requests are required for ResourceQuota to work. Users would like to apply these quotas in namespaces where operators are deployed, to limit consumption on the cluster cores.

## Where

Create a new validator to check such as (ResourcesRequestsValidator). 

c/c @dmesser

**Comment by camilamacedo86** [comment]
Hi, @tlwu2013 and @dmesser, 

So, concerns were raised against adding the validator to enforce/fail when the requested resource is not set. In this way, I'd like to add here and share the mainly strongest argumentations for both cases:  

The motivation to mandatory ask for authors to set at least the resource request is: 

- If a LimitRange is activated in a namespace for computing resources like CPU and memory, users must specify requests or limits for those values. Otherwise, the system may reject Pod creation.
- If a resourQuota be configured and the pods do not have at least requests or limits for those values the system may reject Pod creation.

And then, the above configuration is commonly adopted and recommended in multi-tenancy and or production clusters where OLM is used usually. More info: https://github.com/operator-framework/operator-sdk/pull/5353/files

The argumentation against making the request resource mandatory is: 
- `We want these operator authors to set GOOD resource requests. To create good resource requests, operator authors will need time and customer usage data`. However, the Operator Authors are able to do tests and benchmarks before publishing their first solution or indeed adopting reasonable batting started values for the requests such as: 

```
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
```
- Usually, we only make mandatory what will explicitly not work well with OLM and that shows to be more an indirectly need/requirement. 

Additionally, an additional idea raise so far was to add giving operators a "badge" in the UI when the operator meets these criteria. 

However, it also shows that everybody agrees that the Operator Author should be hammered with warnings.

IHMO: The argumentation to add the requested resource as mandatory seems stronger. But, we can also get started by warning and be revisiting it in the future as well.  

c/c @kevinrizza @awgreene @fgiloux
